# Generated by Django 2.2.13 on 2020-07-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainwheel',
            old_name='track_id',
            new_name='trackid',
        ),
    ]
