# Generated by Django 2.2.13 on 2020-07-09 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_mainmustbuy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainMustBuy',
            new_name='HomeMustBuy',
        ),
        migrations.RenameModel(
            old_name='MainWheel',
            new_name='HomeNav',
        ),
        migrations.RenameModel(
            old_name='MainNav',
            new_name='HomeWheel',
        ),
        migrations.AlterModelTable(
            name='homenav',
            table='nav',
        ),
        migrations.AlterModelTable(
            name='homewheel',
            table='wheel',
        ),
    ]
