# Generated by Django 2.2.13 on 2020-07-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_honeshow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HoneShow',
            new_name='HomeShow',
        ),
    ]
